cargo-features = ["edition2024"]
[package]
name = "cpi"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
borsh-derive = "1.5.7"
solana-program = "2.2.1"
[lib]
crate-type=["cdylib","lib"]
